FROM fedora:35
RUN dnf install -y squid openssl && dnf clean all
# TLS Setup - Generate TLS Certs - For a real use case you want to generate this outside the container and bind the directory later
RUN mkdir -p /etc/squid/tls/ && \
    openssl req -new -newkey rsa:2048 -sha256 -days 3650 -nodes -x509 -extensions v3_ca \
    -keyout /etc/squid/tls/squid-ca-key.pem -out /etc/squid/tls/squid-ca-cert.pem \
    -subj "/C=ES/ST=Valencia/L=Valencia/O=Squid Security/OU=IT/CN=squidproxy.local" && \
    cat /etc/squid/tls/squid-ca-key.pem /etc/squid/tls/squid-ca-cert.pem > /etc/squid/tls/squid-ca-cert-key.pem && \
    chmod 600 /etc/squid/tls/*.pem
# TLS Setup - Generate TLS DB used by Squid - For a real use case you want to generate this outisde the container and bind the directory later
RUN mkdir -p /var/lib/squid && /usr/lib64/squid/security_file_certgen -c -s /var/lib/squid/tsl_db -M 10MB && \
    chown -R squid:squid /var/lib/squid
RUN chown -R squid:squid /etc/squid
USER squid
EXPOSE 3128
CMD ["/usr/sbin/squid", "-N", "-d", "1", "-f", "/etc/squid/squid.conf"]
ENTRYPOINT ["/usr/sbin/squid"]
